Traceback (most recent call last):
  File "/opt/anaconda3/envs/vlxenv/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/anaconda3/envs/vlxenv/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/anaconda3/envs/vlxenv/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/anaconda3/envs/vlxenv/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/anaconda3/envs/vlxenv/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/anaconda3/envs/vlxenv/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/envs/vlxenv/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/anaconda3/envs/vlxenv/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import veloxchem as vlx
import multipsi as mtp

O2_xyz="""2

O 0.0 0.0 -0.6
O 0.0 0.0  0.6
"""
molecule=vlx.Molecule.from_xyz_string(O2_xyz)
molecule.set_multiplicity(3)
basis = vlx.MolecularBasis.read(molecule,"cc-pvdz")

scfdrv = vlx.ScfUnrestrictedDriver()
scfdrv.compute(molecule, basis)
uhf_orbs = scfdrv.natural_orbitals()

space=mtp.OrbSpace(molecule,uhf_orbs)
space.CAS(6,4)
mcscfdrv=mtp.McscfDriver()
mcscfdrv.compute(molecule,basis,space)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn [1], line 18[0m
[1;32m     15[0m uhf_orbs [38;5;241m=[39m scfdrv[38;5;241m.[39mnatural_orbitals()
[1;32m     17[0m space[38;5;241m=[39mmtp[38;5;241m.[39mOrbSpace(molecule,uhf_orbs)
[0;32m---> 18[0m [43mspace[49m[38;5;241;43m.[39;49m[43mCAS[49m([38;5;241m6[39m,[38;5;241m4[39m)
[1;32m     19[0m mcscfdrv[38;5;241m=[39mmtp[38;5;241m.[39mMcscfDriver()
[1;32m     20[0m mcscfdrv[38;5;241m.[39mcompute(molecule,basis,space)

[0;31mAttributeError[0m: 'OrbSpace' object has no attribute 'CAS'
AttributeError: 'OrbSpace' object has no attribute 'CAS'

